version: '3'
services:
  redis:
    image: redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
